apiVersion: v1
kind: Pod
metadata:
  name: resources-demo
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:  # minimum value 
          memory: 60Mi
          cpu: 100m
          # provide equal or more than requests
        limits: # maximum value 
          memory: 100Mi
          cpu: 120m

