apiVersion: v1
kind: Pod
metadata:
  name: env-demo
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: course
          value: devsecops
        - name: trainer
          value: sivakumar

#if we maintain the env variables outside of image that is good because we no nood to build the image everytime